[build]
  base = "/"
  publish = "/out"
  command = "next build && next export"
  functions = "functions/"

[context.deploy-preview.enviroment]
  NODE_ENV = 'production'

[context.production.enviorment]
  NODE_ENV = 'production'

[context.branch-deploy.enviorment]
  NODE_ENV = 'production'
  
[[ redirects ]]
  from = "https://sunnygolovinedotcom.netlify.app"
  to = "https://sunnygolovine.com"
  status = 301
  force = true

# FLoC Off Google
# https://developer.chrome.com/blog/floc/#how-can-websites-opt-out-of-the-floc-computation
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[ plugins ]]
  package = "netlify-plugin-cache-nextjs"

